### PR TITLE
Add descriptions for font generator

### PR DESCRIPTION
**Pull request by the-this-pointer**
Based on your excellent library, I made a font generator for one of my projects. I saw in the issues that others also needed a font generator for the library. 
My font generator is in the early stages, but I think it might help them and save their time.

### CODE REVIEW

**Comment by the-this-pointer** [comment]
Resolves #14 , #4 , 
It can resolve #9 with some modification on the generator and library also.

**Comment by 4ilo** [comment]
This looks very promising!
I have one remark: 
Maybe provide a pre-build binary in the releases tab of your project so people can just use the program, or provide at least some compilation/installation instructions. Right now i have to reverse engineer the build process of your program.

**Comment by the-this-pointer** [comment]
Sure, you are right.
I added the build instructions and also a pre-release to the repository.
Thanks for your suggestion.
https://github.com/the-this-pointer/glcd-font-calculator/releases

**Comment by 4ilo** [comment]
Thanks!

**Pull request merged**
